# Generated by Django 5.2.17 on 2026-09-22 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g. Canned Products, Indian Premium Tea)', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly slug (e.g. canned-products)', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description of this category')),
                ('image', models.ImageField(blank=True, help_text='Upload category display photo', null=True, upload_to='categories/')),
                ('static_fallback_image', models.CharField(blank=True, help_text='Default static image path if no image uploaded', max_length=255)),
                ('item_count_label', models.CharField(blank=True, help_text="Optional custom badge text (e.g. '8 Products' or 'Wholesale Supply'). Leave empty to auto-calculate.", max_length=100)),
                ('is_featured', models.BooleanField(default=True, help_text='Display on homepage categories showcase')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order sequence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(help_text='Unique Product ID (e.g. prod-gl-toor-dal, prod-gl-evaporated-milk-410g)', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(default='GreenLand Food Stuff', max_length=150)),
                ('price', models.DecimalField(decimal_places=3, default=0.0, help_text='Price in KD (e.g. 0.350 or 5.500)', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=3, help_text='Original price before discount in KD', max_digits=10, null=True)),
                ('weight', models.CharField(default='1 KG', help_text='Weight or volume (e.g. 410g, 1 KG Pouch, 20 KG Bulk Sack)', max_length=100)),
                ('unit', models.CharField(blank=True, default='pack', help_text='Packing unit (e.g. tin, retail pack, commercial sack)', max_length=100)),
                ('stock', models.PositiveIntegerField(default=100)),
                ('availability', models.CharField(choices=[('in_stock', 'In Stock'), ('coming_soon', 'Coming Soon'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=30)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage New Arrivals section')),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular item')),
                ('is_new', models.BooleanField(default=False, help_text='Mark as New Arrival')),
                ('is_active', models.BooleanField(default=True, help_text='Show in storefront')),
                ('description', models.TextField(blank=True)),
                ('specs', models.JSONField(blank=True, default=dict, help_text='Key-value specifications (Brand, Net Weight, Origin, etc.)')),
                ('primary_image', models.ImageField(blank=True, help_text='Main product photo', null=True, upload_to='products/')),
                ('static_image_path', models.CharField(blank=True, help_text='Fallback static image path', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='GreenLand Analogue Evaporated Milk', max_length=255)),
                ('subtitle', models.CharField(default='Rich, Smooth & Delicious', max_length=255)),
                ('arabic_title', models.CharField(blank=True, default='شبيه حليب مبخر', max_length=255)),
                ('formulation', models.CharField(blank=True, default='Replaced Milk Fat with Vegetable Oil', max_length=255)),
                ('badge_text', models.CharField(default='Coming Soon', max_length=100)),
                ('net_weight', models.CharField(default='410g', max_length=100)),
                ('brand', models.CharField(default='GreenLand Food Stuff', max_length=150)),
                ('image', models.ImageField(blank=True, help_text='Upload advertisement poster photo', null=True, upload_to='banners/')),
                ('static_image_path', models.CharField(blank=True, default='/static/images/greenland-evaporated-milk-ad.jpg', max_length=255)),
                ('whatsapp_text', models.CharField(blank=True, default='Hello Greenland Foodstuff, I am inquiring about GreenLand Analogue Evaporated Milk (410g).', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
            options={
                'verbose_name': 'New Arrival Advertisement Banner',
                'verbose_name_plural': 'New Arrival Advertisement Banners',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional gallery photo for this product', upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Gallery Image',
                'verbose_name_plural': 'Product Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
