# Generated by Django 5.2.17 on 2026-09-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('code', models.CharField(help_text='Unique brand code (greenland, 88, 777)', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Brand display name (e.g. GreenLand Food Stuff, 88 Brand, 777 Brand)', max_length=150)),
                ('tagline', models.CharField(blank=True, help_text='Short brand subtitle or quality promise', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brand background and history')),
                ('logo', models.ImageField(blank=True, help_text='Brand logo image', null=True, upload_to='brands/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display sequence')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Brand777Product',
            fields=[
            ],
            options={
                'verbose_name': '777 Brand Product',
                'verbose_name_plural': '⭐ 777 Brand Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Brand88Product',
            fields=[
            ],
            options={
                'verbose_name': '88 Brand Product',
                'verbose_name_plural': '🌾 88 Brand Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='GreenLandProduct',
            fields=[
            ],
            options={
                'verbose_name': 'GreenLand Product',
                'verbose_name_plural': '🌿 GreenLand Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.product',),
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'All Products (Master List)', 'verbose_name_plural': '📦 All Products (Master Catalog)'},
        ),
        migrations.AddField(
            model_name='product',
            name='brand_code',
            field=models.CharField(choices=[('greenland', 'GreenLand Food Stuff'), ('88', '88 Brand'), ('777', '777 Brand')], db_index=True, default='greenland', help_text='Select brand (GreenLand, 88 Brand, or 777 Brand)', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='GreenLand Food Stuff', help_text='Display brand title', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(help_text='Unique Product ID (e.g. prod-gl-toor-dal, prod-88-ajwain-seeds, prod-777-asafoetida-100g)', max_length=100, primary_key=True, serialize=False),
        ),
    ]
