services:
  - type: web
    name: greenland-store
    runtime: python
    plan: free
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn greenland_store.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
